name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  verifier:
    timeout-minutes: 30
    concurrency:
      group: opencode-verifier-${{ github.ref }}
      cancel-in-progress: true
    if: |
      contains(github.event.comment.body, ' /vr') ||
      startsWith(github.event.comment.body, '/vr') ||
      contains(github.event.comment.body, ' /verifier') ||
      startsWith(github.event.comment.body, '/verifier')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Run opencode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_VERIFIER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode/mimo-v2.5-free
          use_github_token: true
          share: true

  coder:
    timeout-minutes: 60
    concurrency:
      group: opencode-coder-${{ github.ref }}
      cancel-in-progress: true
    if: |
      contains(github.event.comment.body, ' /cr') ||
      startsWith(github.event.comment.body, '/cr') ||
      contains(github.event.comment.body, ' /coder') ||
      startsWith(github.event.comment.body, '/coder')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Run opencode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_CODER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode/mimo-v2.5-free
          use_github_token: true
          share: true
